version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: codex-completions-api:local
    environment:
      - PORT=${PORT:-11435}
      - PROXY_API_KEY=${PROXY_API_KEY?set-in-env}
      - CODEX_MODEL=${CODEX_MODEL:-gpt-5}
      - PROXY_SANDBOX_MODE=${PROXY_SANDBOX_MODE:-danger-full-access}
      - PROXY_CODEX_WORKDIR=${PROXY_CODEX_WORKDIR:-/tmp/codex-work}
      - PROXY_ENABLE_CORS=true
      - PROXY_CORS_ALLOWED_ORIGINS=${PROXY_CORS_ALLOWED_ORIGINS:-http://localhost,https://localhost}
      - PROXY_TIMEOUT_MS=${PROXY_TIMEOUT_MS:-300000}
      - PROXY_IDLE_TIMEOUT_MS=${PROXY_IDLE_TIMEOUT_MS:-15000}
      - PROXY_STREAM_IDLE_TIMEOUT_MS=${PROXY_STREAM_IDLE_TIMEOUT_MS:-300000}
      - PROXY_SSE_KEEPALIVE_MS=${PROXY_SSE_KEEPALIVE_MS:-15000}
      - PROXY_SSE_MAX_CONCURRENCY=${PROXY_SSE_MAX_CONCURRENCY:-4}
      - PROXY_MAX_CHAT_CHOICES=${PROXY_MAX_CHAT_CHOICES:-5}
      - CODEX_BIN=${CODEX_BIN:-/usr/local/lib/codex-cli/bin/codex.js}
      - CODEX_HOME=/app/.codex-api
    volumes:
      - ./.codex-api:/app/.codex-api
    ports:
      - 127.0.0.1:11435:11435
    restart: unless-stopped
