name = "codex-preflight-logger"
main = "src/index.js"
compatibility_date = "2024-10-03"
account_id = "fb990b91157a362fc63091bf2579ecbd"
workers_dev = false

 [observability.logs]
 enabled = true

routes = [
  { pattern = "codex-dev.onemainarmy.com/*", zone_name = "onemainarmy.com" },
  { pattern = "codex-api.onemainarmy.com/*", zone_name = "onemainarmy.com" }
]
