name: Bug report
description: Report a problem with the Codex OpenAI-compatible proxy
labels: [bug]
body:
  - type: input
    id: summary
    attributes:
      label: Summary
      description: One-line description of the bug
      placeholder: e.g., Streaming crashes when include_usage=true
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide minimal reproduction steps and inputs (mask secrets)
      placeholder: |
        1. Request
        2. Response (headers/body)
        3. Raw SSE transcript (if streaming)
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
    validations:
      required: true
  - type: checkboxes
    id: env
    attributes:
      label: Environment
      options:
        - label: DEV (project-local .codev)
        - label: PROD (Traefik + Cloudflare)
        - label: Other (describe in notes)
  - type: input
    id: version
    attributes:
      label: Proxy commit/branch
      placeholder: e.g., main@abcdef1
  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Attach snippets (mask secrets). Include PROXY_DEBUG_PROTO=1 when helpful.
  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
