version: v1
path: test-results/chat-completions/keploy
command: ./scripts/keploy-start-server.sh
cmdType: shell
port: 11435
proxyPort: 16789
dnsPort: 26789
debug: false

test:
  command: ./scripts/keploy-start-server.sh
  delay: 1s
  apiTimeout: 10s
  ignoreOrdering: false
  globalNoise:
    - type: body
      noise:
        - path: $.stream[*].data.id
        - path: $.stream[*].data.created
        - path: $.id
        - path: $.created

record:
  filters:
    http:
      - method: GET
        pathRegex: ^/healthz$
  recordTimer: 0s

bypassRules:
  - method: GET
    pathRegex: ^/healthz$
