name: CI

on:
  push:
    branches: [ main-p, chore/**, feat/**, fix/** ]
  pull_request:
    branches: [ main-p ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci || npm install

      - name: Lint
        run: npm run lint

      - name: Prettier check
        run: npm run format:check

      - name: Install Playwright deps
        run: npx playwright install --with-deps chromium

      - name: Unit tests
        run: npm run test:unit

      - name: Integration tests
        run: npm run test:integration

      - name: E2E tests (Playwright)
        env:
          PROXY_API_KEY: codex-ci
        run: npm test

