name: CI

on:
  push:
    branches: [main, main-p, chore/**, feat/**, fix/**]
  pull_request:
    branches: [main, main-p]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            code:
              - 'server.js'
              - 'src/**'
              - 'auth/**'
              - 'scripts/**'
              - 'playwright*.ts'
              - 'vitest.config.ts'
              - 'eslint.config.mjs'
              - 'package.json'
              - 'package-lock.json'
              - 'Dockerfile'
              - 'docker-compose.yml'
              - 'compose*.yml'
              - 'tests/**'
              - '.github/workflows/**'
              - '!docs/**'
              - '!**/*.md'
              - '!**/*.{png,jpg,jpeg,svg,gif}'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Install dependencies
        run: npm ci || npm install

      - name: Format check
        run: npm run format:check

      - name: Lint (JS)
        run: npm run lint

      - name: Install Playwright deps (for tests)
        if: steps.changes.outputs.code == 'true'
        run: npx playwright install --with-deps chromium

      - name: Run tests (unit+integration+e2e)
        if: steps.changes.outputs.code == 'true'
        env:
          PROXY_API_KEY: codex-ci
        run: npm run test:all

      - name: Skip tests (docs-only change)
        if: steps.changes.outputs.code != 'true'
        run: echo "Docs-only change detected; skipping test suite."
